src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state = 0;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_published;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles")
     * @Assert\NotBlank
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article")
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $home;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getDatePublished(): ?\DateTimeInterface
    {
        return $this->date_published;
    }

    public function setDatePublished(?\DateTimeInterface $date_published): self
    {
        $this->date_published = $date_published;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

   public function __toString()
   {
       return $this->getTitle();
   }

   public function getHome(): ?int
   {
       return $this->home;
   }

   public function setHome(?int $home): self
   {
       $this->home = $home;

       return $this;
   }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository, CommentRepository $commentRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $article = $articleRepository->findAll(),
            'comment' => $commentRepository->findBy(['article' => $article]),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if( $this->getUser() == $article->getAuthor() | $this->getUser()->hasRole('ROLE_ADMIN')){

            if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($article);
                $entityManager->flush();

                if($this->getUser() == $article->getAuthor()){
                    return $this->redirectToRoute('article_own');
                }
                else{
                    return $this->redirectToRoute('article_index');
                }                
            }

        }

        else{
            $this->addFlash("danger", "don't have rights on it");
            return $this->redirectToRoute('index');
        }        
    }

    /**
     * @Route("/{id}/adminpublished", name="published")
     */
    public function published(Request $request, Article $article): Response
    {
        if( $this->getUser() == $article->getAuthor() | $this->getUser()->hasRole('ROLE_ADMIN')){

            if ($article->getState() == false) {
                
                $article->setState(true);
                $article->setDatePublished(new \DateTime());
                               
            }
            else{
                $article->setState(false);
                $article->setDatePublished(null);
            }

            $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($article);
                $entityManager->flush();

            return $this->redirectToRoute('article_index');


        }

        else{
            $this->addFlash("danger", "don't have rights on it");
            return $this->redirectToRoute('index');
        }        
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article List{% endblock %}

{% block body %}
{{ include('admin/table-scroll.html.twig') }}
{{ include('admin/admin-menu.html.twig') }}
<h1>Article List | {{ articles|length }}</h1>

<table class="table">
    <thead>
        <tr>
            <th>Score</th>
            <th>Title</th>
            <th>Category</th>
            <th>Author</th>
            <th>Created</th>
            <th>Published</th>
            <th>Actions</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <td>

                {% set total_note = 0 %}
                {% set n = 0 %}

                {% for comments in article.comments %}

                {% set total_note = total_note + comments.note %}
                {% set n = n + 1 %}

                {% endfor %}
                {% if n == 0  %}{% set total_note = 0 %}
                {% else %}
                {% set total_note = total_note / n %}
                {% endif %}

                {% if total_note == 0 %}
                pas de note
                {% else %}
                {{total_note}}
                {% endif %}

            </td>
            <td>{{ article.title }}</td>
            <td>{{ article.category.title }}</td>
            <td>
                {% if article.author.id == app.user.id %}
                <span class="text-danger font-weight-bold">You</span>
                {% else %}
                {{ article.author.nom|upper }} {{ article.author.prenom|capitalize }}
                {% endif %}
            </td>
            <td>{{ article.dateCreated ? article.dateCreated|date('d/m/Y') : '' }}</td>
            <td>{{ article.state ? article.datePublished|date('d/m/Y') : 'No' }}</td>
            <td>
                {% if article.state == null %}
                <h4><a class="btn btn-success" href=" {{ path('published', {'id': article.id})}} ">Publish
                        article</h4></a>
                {% else %}
                <h4><a class="btn btn-secondary" href=" {{ path('published', {'id': article.id})}} ">Hide
                        article</h4></a>
                {% endif %}</td>
            <td>
                <a href="{{ path('article_show', {'id': article.id}) }}">show</a>
                {% if article.author.id == app.user.id %}
                <a href="{{ path('artown_edit', {'id': article.id}) }}">edit</a>
                {% endif %}
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="7">no records found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
<h1>Article</h1>
{% if article.state == null %}
<h4><a class="btn btn-success" href=" {{ path('article_published', {'id': article.id})}} ">Publish article</h4></a>
{% else %}
<h4><a class="btn btn-secondary" href=" {{ path('article_published', {'id': article.id})}} ">Hide article</h4></a>
{% endif %}



<table class="table">
    <tbody>
        <tr>
            <th>Title</th>
            <td>{{ article.title }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ article.content }}</td>
        </tr>
        <tr>
            <th>Date_created</th>
            <td>{{ article.dateCreated ? article.dateCreated|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Date_published</th>
            <td>{{ article.state ? article.datePublished|date('d/m/Y  H:i:s') : 'No' }}</td>
        </tr>

        <tr>
            <th>
                {% if article.author.id == app.user.id %}
                <a class="btn btn-primary" href="{{ path('artown_edit', {'id': article.id}) }}">edit</a>
                {% endif %}</th>
            <td>{{ include('article/_delete_form.html.twig') }}</td>
        </tr>
    </tbody>
</table>


<br />
{% if is_granted('ROLE_ADMIN') %}
<a class="btn btn-warning" href="{{ path('article_index') }}">back to all article</a>
<a class="btn btn-info" href="{{ path('article_own') }}">back to my article</a>
{% else %}
<a href="{{ path('article_own') }}">back to article</a>
{% endif %}

{% endblock %}